---
language: shell
dist: xenial
sudo: required
os: linux

jobs:
include:
    - python: 3.7
      os: linux
      arch: ppc64le
      env:
       - DOWNLOAD_OPENBLAS=1
       - ATLAS=None
    - python: 3.7
      os: linux
      arch: s390x
      env:
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None
