---
os: linux
dist: xenial
arch: s390x

jobs:
  include:
  - language: cpp
    compiler: clang
    arch: ppc64le
    script:
      - g++ -nostartfiles main.cpp
      
       - language: node_js
    node_js:
      - node
    script:
      - node hello.js
       arch:
      - s390x


jobs:
  include:
  - arch: ppc64le
  - language: python
    script:
      - chmod u+x charcount.py
      - python charcount.py

  - language: ruby
  - arch: s390x
    script:
      - return 0
